### ISSUE TITLE
HttpTransport "TimedOut" error with Search example

### ISSUE THREAD

**Issue by raleighlittles** [ramsayleung/rspotify#502]
**Describe the bug**

Trying to run a very simple album query example and encountering this error. 

```
called `Result::unwrap()` on an `Err` value: Http(Transport(Transport { kind: Io, message: None, url: Some(Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("accounts.spotify.com")), port: None, path: "/api/token", query: None, fragment: None }), source: Some(Custom { kind: TimedOut, error: "timed out reading response" }) }))
```

**To Reproduce**

Code snippet:

```rust
// main.rs
use rspotify::clients::BaseClient;
use rspotify::model::SearchType;

fn main() {
    println!("Loading credentials from .env file ..");
    let creds_from_env_file = rspotify::Credentials::from_env().unwrap();
    println!("Credentials loaded! Creating client obj.. ");
    let spotify_cli_obj = rspotify::ClientCredsSpotify::new(creds_from_env_file);

    // Obtaining the access token - must be done before any query is made
    spotify_cli_obj.request_token().unwrap();

    let album_query = "album:arrival artist:abba";
    let result = spotify_cli_obj.search(album_query, SearchType::Album, None, None, Some(10), None);
    match result {
        Ok(album) => println!("Searched album: {album:?}"),
        Err(err) => println!("Search error! {err:?}"),
    }
}
```

My Cargo.toml file:

```toml
[package]
name = "to_spotify"
version = "0.1.0"
edition = "2021"

[dependencies]
rspotify = { version = "0.13.3",default-features = false,features = ["env-file", "client-ureq", "ureq-rustls-tls"]}
dotenv = "0.15.0"
```

My version info:

```
info: The currently active `rustc` version is `rustc 1.82.0 (f6e511eec 2024-10-15)`
cargo 1.82.0 (8f40fc59f 2024-08-21)
```

I have the usual Rust folder structure

```
├── Cargo.lock
├── Cargo.toml
├── .env
├── README.md
└── src
    └── main.rs

2 directories, 5 files
```

and my env file has `RSPOTIFY_CLIENT_ID` and `RSPOTIFY_CLIENT_SECRET` defined that I got from the spotify developer dashboard here https://developer.spotify.com/dashboard/
